### ISSUE TITLE
what is moon.getGeocentricEquatorialSphericalJ2000Coordinates?

### ISSUE THREAD

**Issue by hjy1210** [andrmoel/astronomy-bundle-js#22]
I guess 
*  moon.getGeocentricEquatorialSphericalJ2000Coordinates() get ICRF/J2000 Astrometric RA & DEC.
*  moon.getGeocentricEquatorialSphericalDateCoordinates() get Apparent RA & DEC.

Above two get different things.

But when I check the file moon.test.js, 
```
it('tests getGeocentricEquatorialSphericalJ2000Coordinates', async () => {
    const {rightAscension, declination, radiusVector} = await moon.getGeocentricEquatorialSphericalJ2000Coordinates();

    expect(round(rightAscension, 6)).toBe(134.68392);
    expect(round(declination, 6)).toBe(13.769656);
    expect(round(radiusVector, 6)).toBe(0.002463);
});

it('tests getGeocentricEquatorialSphericalDateCoordinates', async () => {
    const {rightAscension, declination, radiusVector} = await moon.getGeocentricEquatorialSphericalDateCoordinates();

    expect(round(rightAscension, 6)).toBe(134.68392);
    expect(round(declination, 6)).toBe(13.769656);
    expect(round(radiusVector, 6)).toBe(0.002463);
});
```
First question : Why two functions test again exactly the same data ?

When I query [Horizon](https://ssd.jpl.nasa.gov/horizons.cgi) with setting
```
Ephemeris Type [change] : | OBSERVER
Target Body [change] : | Moon [Luna] [301]
Observer Location [change] : | Geocentric [500]
Time Span [change] : | Start=1992-4-12, Stop=1992-4-13, Step=1 d
Table Settings [change] : | QUANTITIES=1,2,4,20; angle format=DEG
Display/Output [change] : | default (formatted HTML)
```
I got data:
```
 Date__(UT)__HR:MN     R.A.___(ICRF)___DEC R.A._(a-appar)_DEC. Azi_(a-appr)_Elev            delta      deldot
*************************************************************************************************************
 1992-Apr-12 00:00     134.79701  13.73679 134.69720  13.76513   .n.a.     .n.a. 0.00246286078084  -0.0116158
 1992-Apr-13 00:00     148.38162   8.45735 148.28675   8.49114   .n.a.     .n.a. 0.00245856966988  -0.0029148
```
Second question :   Where is the origin of data 134.68392 used to test rightAscension.

**Comment by andrmoel** [comment]
You are right!

Both functions do have the same implementation, which is totally wrong.
The abstract class AstronomicalObject is forcing me the implementation of both methods.
For simplicity reasons I copy pasted.

Its definitely something which needs to be fixed.

About your second question:
I used Meeus's example from Chapter 47 as reference data.
In his example he gives the R.A. for with: 134.688470°. I interpret the deviating decimal places as rounding errors.
I also tested my data against calsky.com which is sadly offline

**Comment by hjy1210** [comment]
Using the following test
```
	test('1992-4-12 TD', () => {
		let T = -0.077221081451
		console.log(eclipticSpherical2equatorialSpherical(133.162655, -3.229166, 368409.7, T))
		console.log(eclipticSpherical2equatorialSpherical(133.167265, -3.229166, 368409.7, T))
	})
```
I got result:
```
console.log
    {
      rightAscension: 134.68390880184128,
      declination: 13.769618083569936,
      radiusVector: 368409.7
    }

      at Object.<anonymous> (__tests__/astronomy-bundle.test.js:238:11)

  console.log
    {
      rightAscension: 134.6884578495407,
      declination: 13.7683284762364,
      radiusVector: 368409.7
    }
```

As you can see 
*  133.162655 is the longitute before nutation correction in longitude
*  133.167265 is the longitute after nutation correction in longitude
*   your testing data 134.68392 cooresponds to data **without** nutation correction
*   data 134.688470 on Meeus  cooresponds to data **with** nutation correction

I guess, for getGeocentricEquatorialSphericalDateCoordinates, we should consider nutation effect,

**Comment by andrmoel** [comment]
You are completely right what you are writing. The methods do give the results **without** nutation correction.
But it is because you are using the wrong method. ;)

If you want the position corrected by nutation, you need to use one of the following methods.

```
getApparentGeocentricEclipticSphericalCoordinates
getApparentGeocentricEquatorialSphericalCoordinates
```

Background:
The function `eclipticSpherical2equatorialSpherical` does not correct the effect of nutation.
There is another function called `correctEffectOfNutation` in `apparentCoordinateCalc.ts`. But this one is not exported and usable in the compiled package.

PS: J2000 methods are still giving wrong results.

**Comment by hjy1210** [comment]
I understand, for solar system objects, there are getApparentGeocentricEquatorialSphericalCoordinates method to get apparent positions.

What I try to do is : put **stars**, moon, sun on the same picture/image.

Because I can not find a valid good way to convert J2000.0 coordinates of stars to apparentGeocentric coordinates in astronomy-bundle.

So I try following this ugly path:
* J2000.0 mean GeocentricEquatorial -> J2000.0 GeocentricEcliptic (use equatorialSpherical2eclipticSpherical)
* J2000.0 GeocentricEcliptic-> date GeocentricEcliptic (use eclipticJ20002eclipticDate)
* add nutation, aberration, refraction effect 
* GeocentricEcliptic -> apparent GeocentricEquatorial (use eclipticSpherical2equatorialSpherical)

Of cause, never succeed.

May be there are some methods in astronomy-bundle I do not discover yet.

**Comment by andrmoel** [comment]
I will provide a function for the precission which converts J2000 (or any other reference frame) into Date.
Let you know, when its done.

**Comment by andrmoel** [comment]
Please have a look at this PR: https://github.com/andrmoel/astronomy-bundle-js/pull/26

I do hope this is what you need. When I compare my results with the results from meeus, I still do have a little error in declination of about 2 arc seconds. I do think this is because I transform from equatorial to ecliptic, do the corrections of aberration and nutation and transform them back to equatorial.

This is how to use it:

```
    const coords = {
        rightAscension: 41.04994167,
        declination: 49.22846667,
        radiusVector: 1,
    };

    const toi = createTimeOfInterest.fromJulianDay(2462088.69);

    const properMotion = {
        rightAscension: 0.0001427083,
        declination: -0.000024861,
    };

    const star = new Star(coords, toi, properMotion);

    const {rightAscension, declination} = await star.getApparentGeocentricEquatorialSphericalCoordinates();

    console.log(
        deg2time(rightAscension),
        deg2angle(declination),
    );
```

The result of this calculation is:
R.A. 2h 46m 14.548s
Dec. 49° 21' 05.655"

**Comment by hjy1210** [comment]
Thank you for your hard work. That is what I want. Very appreciated!

But, where is the Star constructor?

**Comment by andrmoel** [comment]
There you go: https://github.com/andrmoel/astronomy-bundle-js#stars-position

Can I close this issue?

**Comment by hjy1210** [comment]
@andrmoel 

Thanks a lot.
