### ISSUE TITLE
About date formats...

### ISSUE THREAD

**Issue by lsandini** [andrmoel/astronomy-bundle-js#63]
I am new to this and just playing around I found this very small difference in results. 

I understood that in the ecliptic heliocentric system, the longitude of earth is 0° a the vernal equinox or spring equinox. However, using the date of spring equinox, the longitude coordinate for Earth seems to be 180° (?!) 

I entered a date as close as possible to the FALL equinox, in 2 formats:
```
const date = new Date('2021-09-23 05:34:14.22');    // +3 hours for my timezone
const toi1 = createTimeOfInterest.fromDate(date);
  // and:
const toi2 = createTimeOfInterest.fromTime(2021, 9, 23, 2, 34, 14.22);
```
Then calculating the position of earth at either toi1 or toi2:
```
let position1 = await earth.getHeliocentricEclipticSphericalJ2000Coordinates();
console.log('longitude:', position1.lon);
```
... I get 2 different longitudes (very small difference though):

```
// longitude: 359.9999983264606
// longitude: 8.174083632184193e-7
```

Why is that ?

**Comment by andrmoel** [comment]
Hey @lsandini,
when you `console.log` your `toi1` and `toi2` objects, you will find the difference. it is about the small 22ms you have added to the seconds.

When you use the Date object it ignores the 14.22 value and just considers 14.00 seconds. So `toi1` is exactly 
```
year: 2021, month: 9, day: 23, hour: 2, min: 34, sec: 14
```

However `toi2` is parsed as
```
year: 2021, month: 9, day: 23, hour: 2, min: 34, sec: 14.22
```

So everything is alright. The difference lies only in this tiny 22ms ;)

PS: Maybe the confusion comes from the exponential presentation. You can also write your output as follow:

```
// longitude: 359.9999983264606 // Using 2021-09-23 05:34:14
// longitude: 0.0000008174 // Using 2021-09-23 05:34:14.22
```
